### ISSUE TITLE
The project doesn't build for iOS with the Facebook and Ironsource extension

### ISSUE THREAD

**Issue by Morgerion** [defold/extension-facebook#55] opened 2023-07-19 18:50 UTC
A recent problem still haunts me - the project doesn't build for iOS with the Facebook and Ironsource extension.

Defold version: 1.4.8
Repo case: [Extension_Test.zip](https://github.com/defold/extension-facebook/files/12099095/Extension_Test.zip)
Log file: [log.txt](https://github.com/defold/extension-facebook/files/12099094/log.txt)

**Comment by britzl** [comment] 2023-07-19 21:02
The issue has been fixed (https://github.com/defold/extender/issues/306) but we have not yet released a new beta build server. It will likely happen tomorrow.

**Comment by britzl** [comment] 2023-07-20 07:02
The fix has been deployed to https://build-stage.defold.com

**Comment by Morgerion** [comment] 2023-07-20 12:23
Yay, the IPA-build is finally complete.
But Apple is pulling back this build.
![image](https://github.com/defold/extension-facebook/assets/7888071/abcb413a-69c7-446d-8377-927558397b23)
If you build on an old build server, everything is submit correctly (I checked it out on another project that doesn't have Facebook).

**Comment by britzl** [comment] 2023-07-20 15:36
Apparently we need to strip bitcode from the libs using `bitcode_strip`. We'll add support for this. Should be available tomorrow.

**Comment by britzl** [comment] 2023-07-20 22:23
Bitcode stripping in this PR: https://github.com/defold/extender/pull/310

**Comment by britzl** [comment] 2023-07-21 05:35
> Bitcode stripping in this PR: [defold/extender#310](https://github.com/defold/extender/pull/310)

@Morgerion This PR has been merged and published to build-stage.defold.com. Please give it a try and let us know if your Apple submission is approved or not.

**Closed by britzl** 2023-07-21 05:35 UTC

**Comment by Morgerion** [comment] 2023-07-21 10:29
Everything has now submitted successfully!
The new version passed in TestFlight with no errors.

**Comment by britzl** [comment] 2023-07-21 10:29
> Everything has now submitted successfully! The new version passed in TestFlight with no errors.

Thank you for confirming that the issue is resolved!
